### ISSUE TITLE
gh-pages linking

### ISSUE THREAD

**Issue by rblades** [nullism/pykwiki#14]
Hi,

I am running into an issue at [http://rblades.github.io/open-notebook](http://rblades.github.io/open-notebook). The Welcome, Posts, and Search link just to rblades.github.io/posts.html, etc.

I have included a screenshot of my config.yaml. 

<img width="1280" alt="screen shot 2015-11-30 at 1 45 16 pm" src="https://cloud.githubusercontent.com/assets/9255906/11481027/def8c45e-9768-11e5-99de-b77761843f45.png">

Cheers

**Comment by nullism** [comment]
Hey there,

Would you mind sharing your links.yaml file? The menu links *should* be using whatever "web_prefix" is set to, and your config looks correct at first glance. We might have a bug on our hands (I should be able to fix it today if that's the case).

Thanks!

**Comment by rblades** [comment]
Yep! Here it is
<img width="1057" alt="screen shot 2015-11-30 at 2 43 51 pm" src="https://cloud.githubusercontent.com/assets/9255906/11482448/cff66d78-9770-11e5-9d3f-1130a5166d0e.png">

**Comment by nullism** [comment]
That is very bizarre indeed.

The Posts and Search links make sense, as the `href` property value is interpreted exactly (so one can link to other resources on the same domain), but the Welcome page (with the `post:` property) most definitely should have `web_prefix` in the actual URL. 

One thing that may have happened is `pykwiki cache` was ran before `web_prefix` was set, and since the `links.yaml` file was unchanged it didn't find any reason to re-cache the links. 

Could you try running `pykwiki cache -f` and let me know if the `web_prefix` is still missing from the Welcome link? 

As for Search and Posts (or any link which uses `href` instead of `post`) you can fix that by either setting the `href` to `/open-notebook/posts.html` and `/open-notebook/search.html` or using `post: posts` and `posts: search`. 

Thanks for helping me track this down!

**Comment by rblades** [comment]
Hey.

It worked! I think I did run `pykwiki cache` before `web_prefix` was set. 

`pykwiki cache -f` fixed the Welcome link.

I changed Posts and Search to `/open-notebook/posts.html` and `/open-notebook/search.html` respectively and ended with a url of `/open-notebook/open-notebook/posts.html` and `/open-notebook/open-notebook/search.html`. 

So I used the `post: posts` and `post: search` method and that fixed the problem.

Cheers!
