### ISSUE TITLE
Source images not copied into docroot folders

### ISSUE THREAD

**Issue by cinxgler** [nullism/pykwiki#6]
Hi,

I've got a source structure like this:

    ├── chie
    │   ├── index.md
    │   └── plan_anual_adquisiciones
    │       ├── admin
    │       │   ├── adicionar_plan_anual.md
    │       │   ├── gestionar_solicitud_de_cambio.md
    │       │   ├── img
    │       │   │   ├── a_vista1.png
    │       │   │   ├── a_vista2.png
    │       │   │   ├── a_vista3.png
    │       │   └── menus.md
    │       ├── admin.md
    │       ├── index.md
    │       ├── soporte.md
    │       ├── usuario
    │       │   ├── adicionar_plan_item.md
    │       │   ├── img
    │       │   │   ├── menu1.png
    │       │   │   ├── menu2.png
    │       │   │   ├── menu3.png
    │       │   │   ├── menu4.png
    │       │   │   ├── menu5.png
    │       │   │   ├── menu6.png
    │       │   ├── menus.md
    │       │   └── solicitar_cambio.md
    │       └── usuario.md
    ├── index.md

When i run `pykwiki cache -f` i would expect get the img folders and its images copied into docroot folders but i get:

    ├── chie
    │   ├── index.html
    │   └── plan_anual_adquisiciones
    │       ├── admin
    │       │   ├── adicionar_plan_anual.html
    │       │   ├── gestionar_solicitud_de_cambio.html
    │       │   └── menus.html
    │       ├── admin.html
    │       ├── index.html
    │       ├── soporte.html
    │       ├── usuario
    │       │   ├── adicionar_plan_item.html
    │       │   ├── menus.html
    │       │   └── solicitar_cambio.html
    │       └── usuario.html
    ├── idx.json
    ├── index.html
    ├── links.json

So the image links get broken as the image folders are not there. Should i copy the images manually or am i missing something in the cache generation?

Thanks in advance.

**Comment by phayz** [comment]
Has there been any progress on this issue? I am experimenting with PyKwiki for my personal blog. So far it looks really easy to use, though I haven't yet published the 'docroot' to my GitHub account.

The only thing which concerns me about PyKwiki is that the most recent change was 5 months ago. I have had some minor difficulty in getting it up and running, so have some suggestions to make, but I'm not sure if it's worth my time if the project has been dropped.

**Comment by nullism** [comment]
Hi Phayz,

I've been spending most of my time working on PyKwiki2, which uses a single theme with "styles" defined by custom SASS, instead of multiple themes that may use Bootstrap or whatever. The major benefit of this is that the HTML templates that make up the core theme can be updated via pip instead of manually copied into place.  

However, if you choose to use PyKwiki 1, any documentation written for PyKwiki should still work with 2.0, only the configuration file will need one or two lines changed.  

The reason this ticket is still open is because what I initially thought was a good idea has now morphed into maybe not such a good idea. Should non-source files be copied to the docroot if they're not explicitly found in the `uploads` folder? What sort of adverse effects could this have for existing installations? Are people keeping "non-public" data in the source folder? 

So... I've left this one open because I can't make a decision. ANY input on this matter is excellent. FWIW, I plan on adding this for PyKwiki2. 

If you're interested in PyKwiki2, the Pycnic project documentation is generated from 2.0, found [here](http://pycnic.nullism.com/docs/).

**Comment by phayz** [comment]
nullism,

Thanks for your reply. I haven't yet put PyKwiki to the test but I think it's great in what it does. I'm not interested in frameworks, libraries etc, but in publishing my blog as simply as possible with my few needed features. PyKwiki does all that I need at the moment.

I'm going to continue and republish my old blog posts using PyKwiki (I wish that was easier to type! :D).

I think the current behaviour in copying the contents of the `uploads` folders is good. A user then knows for sure where images and videos need to be stored and so knows the path to be used in a blog post. I see no reason to change the current behaviour.

**Comment by nullism** [comment]
This has been implemented in Pykwiki 2.
